### ISSUE TITLE
scan qr code

### ISSUE THREAD

**Issue by thisfardi** [Zobin33/Anu-Wabot#5]
mohon bantuannya bang gmn caranya scan qr codenya diperlambat?
karna terlalu cepet kluar qr baru jd gagal trus discan qr.
terima kasih

**Comment by Zobin33** [comment]
Done Pak

**Comment by thisfardi** [comment]
lib\command\menu.js:78
            "rowId":prefix[0]+`menu${b}`,
                          ^

TypeError: Cannot read properties of undefined (reading '0')

error pak manggil zmenu
terima kasih

**Comment by Zobin33** [comment]
Done Pak Dicoba
